import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/layouts/Footer";
import Header from "../components/layouts/Header";
//import { Provider } from 'react-redux';
//import { AppProps } from 'next/app';
//import { store } from '../services/store';
//{/*<Provider store={store}></Provider*/}>
import { Providers } from './providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        {/*<script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const originalConsoleError = console.error;
                console.error = function(...args) {
                  if (args[0] && args[0].includes('Warning: Extra attributes from the server')) {
                    return;
                  }
                  originalConsoleError.apply(console, args);
                };
              })();
            `,
          }}
        />*/}
      </head>
      <body className={inter.className}>
        <Header/>
          <div>
              <Providers>{children}</Providers>
          </div>
        <Footer/>
      </body>
    </html>
  );
}
